services:
  web:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: app-nginx
    volumes:
      - ./:/app
      - ./docker/nginx/conf:/etc/nginx
    ports:
      - 8080:8080
    depends_on:
      - app

  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: app-php
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini # cp php.ini-development php.ini
    expose:
      - 9000
